# Generated by Django 3.0.5 on 2020-04-08 15:35

from django.db import migrations

def seed(apps, schema_editor):
    Houses = apps.get_model('houserent', 'Houses')
    City = apps.get_model('houserent', 'City')
    desmoines = Decade(name="des moines")
    westdesmoines = Decade(name="west des moines")
    aims = Decade(name="aims")
    altoona = Decade(name="altoona")
    desmoines.save()
    westdesmoines.save()
    aims.save()
    altoona.save()
    Houses(city = desmoines, name='civic center apt', address='1205 52nd st,des moines',amt='1000$', description='beautifull home', image_url='https://wp-tid.zillowstatic.com/7/buy-vs-rent-215f3b.jpg').save()
    Houses(city = desmoines, name='park west apt',address='1205 52nd st,des moines',amt='1000$', description='beautifull home', image_url='https://wp-tid.zillowstatic.com/7/buy-vs-rent-215f3b.jpg').save()
    Houses(city = westdesmoines, name='washington heights', address='1205 52nd st,des moines',amt='1000$',description='beautifull home', image_url='https://wp-tid.zillowstatic.com/7/buy-vs-rent-215f3b.jpg').save()
    Houses(city = westdesmoines, name='polo club',address='1205 52nd st,des moines',amt='1000$', description='beautifull home', image_url='https://wp-tid.zillowstatic.com/7/buy-vs-rent-215f3b.jpg').save()
    Houses(city = aims, name='joardan creek',address='1205 52nd st,des moines',amt='1000$', description='beautifull home', image_url='https://wp-tid.zillowstatic.com/7/buy-vs-rent-215f3b.jpg').save()
    Houses(city = altoona, name='millcivic', address='1205 52nd st,des moines',amt='1000$',description='beautifull home', image_url='https://wp-tid.zillowstatic.com/7/buy-vs-rent-215f3b.jpg').save()
def fallow(apps, schema_editor):
    House = apps.get_model('houserent', 'House')
    City = apps.get_model('houserent', 'City')
    City.objects.all().delete()
    Houses.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('houserent', '0001_initial'),
    ]

    operations = [
            migrations.RunPython(seed, fallow)
    ]
